# Testing done in tox - setup env with 2.8
sudo: false
language: python
python:
  - "3.5"

before_script:
  - bash setup_elasticsearch.sh
  - sleep 5

after_script:
  - kill $(cat elasticsearch-*/pidfile)
  - rm -rf elasticsearch-*

# All envs
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=pep8

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
