sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install -r requirements.txt
    - pip install pep8
    - pip install coveralls
    - pip install mock
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
    - coverage run --source=tantale test.py
    - pep8 src setup.py test.py

after_success:
    coveralls
