sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install -r requirements.txt
    - pip install pep8
    - pip install coveralls
    - pip install mock

script:
    - coverage run --source=src/tantale test.py
    - pep8 src setup.py test.py

after_success:
    coveralls
