#!/bin/sh
#
# tantale
#
# chkconfig: 2345 25 75
# description: Tantale is monitoring daemon
# processname: python
# config: /etc/tantale/tantale.conf
# pidfile: /var/run/tantale.pid
### BEGIN INIT INFO
# Provides:          tantale
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tantale is monitoring daemon
# Description:       Tantale is monitoring daemon
### END INIT INFO

NAME=tantale
DAEMON=tantale
PIDFILE=/var/run/tantale.pid
SCRIPTNAME=/etc/init.d/tantale
LOCKDIR=/var/lock/subsys
LOCKFILE=/var/lock/subsys/tantale

. /etc/rc.d/init.d/functions

start() {
  if [ -d "${LOCKDIR}" -a -w "${LOCKDIR}" ]
  then
    local pid
    __pids_var_run $NAME || rm -f "${LOCKFILE}"
    if ( set -o noclobber; echo "$$" > "${LOCKFILE}") 2> /dev/null;
    then
      true
    else
      echo "Failed to acquire lockfile: ${LOCKFILE}."
      echo "Held by $(cat ${LOCKFILE})"
      echo_failure
      return 1
    fi
  fi

  echo -n $"Starting $NAME: "
  daemon --pidfile $PIDFILE $DAEMON $DAEMON_ARGS
  retval=$?
  if [ $retval -eq 0 ]; then
    echo_success
    echo
  else
    echo_failure
    echo
  fi
  return $retval
}

stop() {
  echo -n $"Stopping $NAME: "
  killproc -p $PIDFILE $NAME
  retval=$?
  if [ $retval -ne 0 ];
  then
    killall -q tantale
  fi
  if [ -e "${LOCKFILE}" ]
  then
    rm -f "${LOCKFILE}"
  fi
  echo
  return $retval
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p $PIDFILE $NAME
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 2
    ;;
esac

exit $?
